// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "mmm":return img`
..........................dddd
..........6...............dd..
..........666666666666...ddd..
..........666666666676...ddd..
.....dd...67666666766766dddd..
.dddddd...66766666676666dddd..
.dddddd...6667777766676ddddd..
.ddddddd..6667dd7777767ddddd..
.......dd.666cd961dd977dddd...
........dd.666dfffdfffbc......
.........dd.6d6dddddddd.......
..........dd6bddedddedb.......
...........ddcdddeebdda.......
............bcbddddddac.......
............caaaabbbaa........
.............a5aaabaa5........
..............aaaaaaaa........
..............aa7aa55.........
..............5a55555.........
..............5a55575.........
..............5a55555.........
..............55a5555.........
..............55aaaaa.........
..............5555555.........
..............aaaaaaa.........
..............a555555.........
.............a5555555.........
............aaaaa5555.........
...........aa55555555.........
..........aa555a555555........
..........a55aaa555555........
.........a555aa5555a755.......
........aa55aa57555a555.......
.......aa55aa555555a555.......
.......a55aa555a555a555a......
........aaaaaaaaaaaaaaaa......
..........bbbb...bbb..........
..........bbb....bbb..........
.........ddd.....ddd..........
........ddd......ddd..........
.......dddd......ddd..........
......dddd.......ddd..........
......ddd.........dd..........
.....ddd..........dd..........
.....dd...........dd..........
....ddd............dd.........
....dd.............ddd........
....dddd.............dd.......
..............................
..............................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
